theme: jekyll-theme-minimal
title: Samantha Kyle
description: This here is my personal website, where you can find out a little more about me! It's still in development so hold on. 

heading: Projects

heading: Resume

heading: Teaching Portfolio

heading: Research Work

heading: Contact Me
